[package]
name = "movie_alert"
version = "0.1.0"
authors = ["Yanhao Zhu <yanhaozhu@gmail.com>"]

[dependencies]
roadrunner = { git="https://github.com/luanzhu/roadrunner", branch="master" }
hyper = { git = "https://github.com/hyperium/hyper", branch = "master" }
serde="1.0"
serde_json = "1.0"
serde_derive="1.0"
log = "0.3.7"
env_logger = "0.4.2"
tokio-core = "0.1.6"